### PR TITLE
Generate results page

### LINKED ISSUE #10: [4H] Generate results page
Probably HTML. Need to find a library for that

### PR DESCRIPTION
**Pull request by RemiBardon**
Fixes #10

- [x] Unhardcode values
- [x] Accept inputs
- [x] Document usage
- [x] Test (kind of done / visual testing)

### CODE REVIEW

**Comment by FlorianDussable** [comment]
```__init__.py``` is pretty much useless if it's empty. It is not a requirement to run Python 3 code and is normally used to describe external module paths to include to the current package.

**Comment by FlorianDussable** [comment]
I don't think that the usage of ```make``` is really needed if it's only to run tests. It's really overkill especially for a Python project. Pytest can be run directly and it's possible to make modifications on environment (such as ```PYTHONPATH```) in a ```conftest.py``` file that is automatically parsed by Pytest.
Also, you normally run multiple test cases with different sample data, and you handle atleast one failure case to make a viable testing environment. If it's only to generate a sample page, then the usage of Pytest is not needed as the tool is based on assertions and exceptions.

**Comment by RemiBardon** [comment]
> `__init__.py` is pretty much useless if it's empty. It is not a requirement to run Python 3 code and is normally used to describe external module paths to include to the current package.

It's there to enable discoverability by pytest. IIRC, pytest wasn't working without it.

**Comment by FlorianDussable** [comment]
Code seems good to me. The usage of typing hints is pretty smart. Well commented.
As we discussed the models will move to a different file afterwards.

**Comment by RemiBardon** [comment]
> I don't think that the usage of make is really needed if it's only to run tests. It's really overkill especially for a Python project. 

It's not what I read, but I have very little knowledge about Python 🤷🏻‍♂️

> Pytest can be run directly and it's possible to make modifications on environment (such as PYTHONPATH) in a conftest.py file that is automatically parsed by Pytest.

Didn't know that, I'll make changes accordingly.

> Also, you normally run multiple test cases with different sample data, and you handle atleast one failure case to make a viable testing environment.

100% agree, but in my case it was just a sample code to manually check if output is OK (which saved a lot of errors).

> If it's only to generate a sample page, then the usage of Pytest is not needed.

It was intended a an "introduction to pytest" which would allow others to write tests once this PR is merged. (I should have done a different PR, but whatever)

**Comment by FlorianDussable** [comment]
> 
> 
> > `__init__.py` is pretty much useless if it's empty. It is not a requirement to run Python 3 code and is normally used to describe external module paths to include to the current package.
> 
> It's there to enable discoverability by pytest. IIRC, pytest wasn't working without it.

I've never encountered this with Pytest, even on Python 2. For me, running ```pytest ./tests``` or even ```pytest ./tests/test_pagegen.py``` would to the trick as it takes less time to explore your tree. If needed, the import statement has to be modified (src.pagegen probably won't work when removing the ```__init__.py``` files)

**Comment by RemiBardon** [comment]
I was just following [pytest "Good Integration Practices"](https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-outside-application-code) 🤷🏻‍♂️

**Comment by FlorianDussable** [comment]
> 
> 
> I was just following https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-outside-application-code 🤷🏻‍♂️

It's no big deal anyways, there's no need to change that for this PR.

**Comment by RemiBardon** [comment]
> If needed, the import statement has to be modified (src.pagegen probably won't work when removing the `__init__.py` files)

I wanted to avoid this, it's one of the reasons why I created the `__init__.py` file.

**Comment by FlorianDussable** [comment]
> 100% agree, but in my case it was just a sample code to manually check if output is OK (which saved a lot of errors).

> It was intended a an "introduction to pytest" which would allow others to write tests once this PR is merged. (I should have done a different PR, but whatever)

Okay. Good answer ;)

**Comment by FlorianDussable** [comment]
> 
> 
> > If needed, the import statement has to be modified (src.pagegen probably won't work when removing the `__init__.py` files)
> 
> I wanted to avoid this, it's one of the reasons why I created the `__init__.py` file.

I understand. This is a good way to describe your tree to Python and therefore to make the import statements easier in your code, especially when you're walking backwards in your tree to import code. But there are other ways to do so, that doesn't require the usage of these ```__init__.py``` files, that are well adapted in projects of this size. It's really no big deal and doesn't need to be changed.

**Comment by RemiBardon** [comment]
I tried removing a `__init__.py` file, and tests broke instantly. I have to keep them for discoverability.

**Comment by FlorianDussable** [comment]
> 
> 
> I tried removing a `__init__.py` file, and tests broke instantly. I have to keep them for discoverability.

It's obviously the ```from src.pagegen import``` that is failing due to the absence of ```__init__.py``` files

**Comment by RemiBardon** [comment]
Is it better now? (I think you can merge)

**Comment by FlorianDussable** [comment]
Do the import works when not defining PYTHONPATH to ```.``` like you did in your makefile ?

**Comment by RemiBardon** [comment]
Looks like it does. Can you try on your computer? (mine did not complain, and `PYTHONPATH` is not set 🤷🏻‍♂️)

**Comment by FlorianDussable** [comment]
Seems good to me. Merging.

**Pull request merged**
